name: Publish docs via GitHub Pages
on:
  push:
    branches: [master]
  workflow_dispatch:
  
permissions: write-all

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      
      - name: Install dependencies
        uses: actions/setup-node@v5
        run: npm install


      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: course.dyalog.com
          REQUIREMENTS: CI/requirements.txt
