name: Publish docs via GitHub Pages
on:
  push:
    branches: [master]
  workflow_dispatch:
  
permissions:
  contents: write
  pages: write

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v6
      
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r CI/requirements.txt

      - name: Deploy docs
        run: |
          mkdocs gh-deploy --force --clean
